### PR TITLE
feat(modal): add support for custom dimensions

### PR DESCRIPTION
**Pull request by HendrikThePendric**
See https://jira.dhis2.org/browse/LIBS-2

### CODE REVIEW

**Review by Mohammer5 — CHANGES_REQUESTED** [review]
No test (not sure what'd be the best test here, but I think jest is more appropriate than cypress)

---

I'm wondering if we should also add `maxWidth` and `maxHeight` props, which would allow the following:
```jsx
<Modal ... height="95vh" width="400px" maxWidth="95vw" />
```

**Review by varl — CHANGES_REQUESTED** [review]
I am wary that this opens up for a lot of bad uses of the Modal. If a Modal needs to be larger than "large", that indicates that whatever we are trying to fit into it should be on its own screen.

I would like to discuss this with @cooper-joe to understand the use cases better.

**Comment by HendrikThePendric** [comment]
> If a Modal needs to be larger than "large", that indicates that whatever we are trying to fit into it should be on its own screen.

That's a bold conclusion IMO, but a good starting point for a conversation nonetheless.

The use-case is to view interpretations of a given visualisation. We want to show the same visualisation as the user is currently viewing, but in the state the visualisation was when the interpretation was written. IMO some sort of modal experience is a great fit with this.

**Comment by HendrikThePendric** [comment]
I have implemented dynamic dimensions using a `fluid` prop now. This comes with two downsides/gotchas/known-issues:
- One point which I decided to leave unaddressed is that when the `position` prop has value `top` (default) or `bottom` the modal has some predefined whitespace above/below. So if you would want to implement a modal with a very large height, say `99vh`, you would have to set both the `fluid` and the `position="middle"` prop on the modal. Otherwise the default `top` position would be applied and the whitespace that comes with that would cause the modal to extend beyond the bottom window border.
- Another point is the layout. In [the fluid modal story](https://pr-828--dhis2-ui.netlify.app/?path=/story/layout-modal--fluid-title-content-primary) you see the buttons (which have been placed in a `ModalActions` component) are high up on the modal, while they should really be aligned with the bottom of the modal. This is because we're now using a `Box` to control the modal's dimensions, and this is not `display: flex`. So if apps want to use a fluid modal with a bottom-aligned modal-footer, they probably need to insert some custom div with dimensions + flexbox. I decided to leave this unaddressed as well.

**Comment by HendrikThePendric** [comment]
Given the two fairly substantial known-issues above, does it even make sense to implement this prop? I know we don't like overriding UI styles, but I almost feel that is a cleaner approach then having to re-implement the layout inside the component and ensuring you set the modal's position to "middle".

**Comment by HendrikThePendric** [comment]
I've discussed this in a bit more detail with @mediremi and decided to close this PR. Adding custom dimension was not an acceptable solution and the alternative comes with too many downsides. In the end the cleanest solution here is just to let apps add style overrides 🤷‍♂️ .

**Pull request closed without merging**
