### PR TITLE
ui@5

### LINKED ISSUE #41: Scope for ui@5
# 5.0.0 scope

- Co-locate UI libraries in repo `dhis2/ui`
- Introduce the `@dhis2/ui` top-level package and main entry-point for the UI libraries.
- Keep `@dhis2/ui-core` and `@dhis2/ui-widgets` as-is:
- - **core**: Ready-to-go building blocks for UI
- - **widgets**: Components that need translations and/or DHIS2 API
- Internal split to:
- - `@dhis2/constants`
- - `@dhis2/icons`

# Upgrade path from 4.x to 5.x

- Generally all imports from either `@dhis2/ui-core`, `@dhis2/ui-widgets`, and `@dhis2/ui-forms` can be replaced by a single namespace: `@dhis2/ui`.
- There are some cases where we have rename a component to avoid name conflicts.
- Some components have been dropped, see the CHANGELOG for more information.

### PR DESCRIPTION
**Pull request by ismay**
Todo:

- [x] Repurpose Field component
- [x] Use new Field component as Wrapper for out *Field components
- [x] Move *Field components to widgets workspace
- [x] Require type="checkbox|radio" on RFF's Field component when using a checkbox or radio input
- [x] Rename *Control components in the forms workspace to *FieldFF (e. g. InputField in widgets; InputFieldFF in forms) (https://github.com/dhis2/ui/pull/59)
- [x] Rename FieldSetField to FieldGroup in widgets and GroupControl to FieldGroupFF (https://github.com/dhis2/ui/pull/59)
- [x] Import changes from upstream packages (see https://dhis2.slack.com/archives/CBM8LNEQM/p1589547747047100, https://varl.dev/Git and https://github.com/dhis2/ui/pull/56#issuecomment-625069940)
- [ ] Archive core and widgets after merge to master

Jan-Gerke:

- [x] Docs update (https://github.com/dhis2/ui/pull/21)
- [x] Transfer component changes, storybook prefix (https://github.com/dhis2/ui/issues/50 & https://github.com/dhis2/ui/pull/60)

Hendrik:

- [x] Menu (https://github.com/dhis2/ui/pull/44)

Ismay:

- [x] Add default translations to components in widgets (https://github.com/dhis2/ui/pull/61)
- [x] Ensure the select is working properly (https://github.com/dhis2/ui/issues/64)
- [x] Export constants (https://github.com/dhis2/ui/pull/56#issuecomment-627902946, https://github.com/dhis2/ui/pull/73)
- [x] Move issues from deprecated repos & close

Closes #41

### CODE REVIEW

**Comment by varl** [comment]
Hi :wave: 

When you are getting ready to release ui@5 and want to freeze the rep dhis2/ui-core; update the description and readme before archiving the repo, e.g. https://github.com/dhis2/ui-forms/

When it comes to pulling in the upstream (ui-core) changes to UI, short notes are available here: https://varl.dev/Git

Basically:

```
git remote add core git@github.com:dhis2/ui-core.git
git subtree pull --prefix=packages/core core master --squash --message 'chore(core): update from upstream'

git remote add widgets git@github.com:dhis2/ui-widgets.git
git subtree pull --prefix=packages/widgets widgets master --squash --message 'chore(widgets): update from upstream'
```

The merge conflicts can be a bit gnarly, so I'd recommend merging the least amount of stuff into dhis2/ui-core or possibly freezing now.

And, if you want me to do the final upstream pull after archiving I can find the time to do so an evening.

Good luck. :five:

**Comment by ismay** [comment]
> Hi 👋
> 
> When you are getting ready to release ui@5 and want to freeze the rep dhis2/ui-core; update the description and readme before archiving the repo, e.g. https://github.com/dhis2/ui-forms/
> 
> When it comes to pulling in the upstream (ui-core) changes to UI, short notes are available here: https://varl.dev/Git
> 
> Basically:
> 
> ```
> git remote add core git@github.com:dhis2/ui-core.git
> git subtree pull --prefix=packages/core core master --squash --message 'chore(core): update from upstream'
> 
> git remote add widgets git@github.com:dhis2/ui-widgets.git
> git subtree pull --prefix=packages/widgets widgets master --squash --message 'chore(widgets): update from upstream'
> ```
> 
> The merge conflicts can be a bit gnarly, so I'd recommend merging the least amount of stuff into dhis2/ui-core or possibly freezing now.
> 
> And, if you want me to do the final upstream pull after archiving I can find the time to do so an evening.
> 
> Good luck. 5️⃣

Cool, thanks for the explanation! Will let you know if we need some assistance 👍

**Comment by Mohammer5** [comment]
- [ ] The storybook stories are not sorted alphabetically anymore
- [ ] The button has an incorrect padding when using an icon without a label

**Comment by ismay** [comment]
>     * [ ]  The storybook stories are not sorted alphabetically anymore
> 
>     * [ ]  The button has an incorrect padding when using an icon without a label
> 
> 
> The `ui-core` and `core` buttons now have different spacing:
> 
>     * https://ui-core.dhis2.nu/demo/?path=/story/button-basic--icon-only
> 
>     * http://localhost:5000/?path=/story/components-core-button--icon
>       (There's no online live demo yet)
> 
> 
> It seems that the new spacing is correct, but the old spacing matches the `Transfer` component's buttons (cc: @cooper-joe)

Thanks! If they're confirmed, would you mind adding them to the top todo list?

**Comment by ismay** [comment]
Also, the transfer story is missing a prefix:

Screenshot 2020-05-07 at 11 14 26

I'll add that after you've added your todos @Mohammer5

**Comment by Mohammer5** [comment]
Related: #60 

@ismay that PR also tackles that issue

**Comment by cooper-joe** [comment]
> The `ui-core` and `core` buttons now have different spacing:
> 
>     * https://ui-core.dhis2.nu/demo/?path=/story/button-basic--icon-only
> 
>     * http://localhost:5000/?path=/story/components-core-button--icon
>       (There's no online live demo yet)
> 
> 
> It seems that the new spacing is correct, but the old spacing matches the `Transfer` component's buttons (cc: @cooper-joe)

Weird. The correct spacing is the one found here: https://ui-core.dhis2.nu/demo/?path=/story/button-basic--icon-only - I'm not sure how the 'new' spacing got in there. Maybe this branch was made before I made the icon-only changes to ui-core.

**Comment by ismay** [comment]
> > The `ui-core` and `core` buttons now have different spacing:
> > ```
> > * https://ui-core.dhis2.nu/demo/?path=/story/button-basic--icon-only
> > 
> > * http://localhost:5000/?path=/story/components-core-button--icon
> >   (There's no online live demo yet)
> > ```
> > 
> > 
> > It seems that the new spacing is correct, but the old spacing matches the `Transfer` component's buttons (cc: @cooper-joe)
> 
> Weird. The correct spacing is the one found here: https://ui-core.dhis2.nu/demo/?path=/story/button-basic--icon-only - I'm not sure how the 'new' spacing got in there. Maybe this branch was made before I made the icon-only changes to ui-core.

@cooper-joe Yeah I suspect that that's because there are some upstream changes that we haven't pulled yet.

**Comment by Mohammer5** [comment]
Padding has been addressed in #65

**Comment by HendrikThePendric** [comment]
One of the ToDos read:
> Constants and icons exports?

I discussed this with @ismay and we decided that it would probably be best to just export the constants for now, and keep the icons internal.

There are several reasons for not exporting the icons right now:
- We haven't got a full set of icons yet, we've just created some that were needed by our components
- The implementation isn't all that consistent yet
- We are still discussing what we want the final product to look like in  https://github.com/dhis2/ui/issues/55

So exposing these icons doesn't add much value, while the likelihood of producing breaking changes on these icons is quite real. This would then trigger a new major version release. If we keep them internal for now, we can introduce them in a minor version bump.

I'll update the ToDo list.

**Pull request merged**
