### PR TITLE
chore(package.json): fix repository urls

### PR DESCRIPTION
**Pull request by ismay**
Our repo urls in package.json were incorrect. Changed them to the new location.

### CODE REVIEW

**Review by Mohammer5 — COMMENTED** [review]
We could also add the "folder" property to the "repository", like so:

```json
{
  "respository": {
    "type": "git",
    "url": "https://github.com/dhis2/ui.git",
    "folder": "packages/core"
  }
}
```

**Comment by ismay** [comment]
> We could also add the "folder" property to the "repository", like so:
> 
> ```json
> {
>   "respository": {
>     "type": "git",
>     "url": "https://github.com/dhis2/ui.git",
>     "folder": "packages/core"
>   }
> }
> ```

I see in the npm docs that they recommend a "directory" key for that? Do you mean that, or is the "folder" key something else?

**Comment by ismay** [comment]
@Mohammer5 I've added the directory keys. Seems like a nice addition 👍

**Comment by ismay** [comment]
We could actually also add [homepage](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#homepage) and [bugs](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#bugs)

**Review by Mohammer5 — APPROVED** [review]
LGTM.
Seems like I somehow thought it was "folder" when it's actually "directory", so your changes are 100% correct

**Pull request merged**
