### PR TITLE
docs(storybook): remove story prefixes

### PR DESCRIPTION
**Pull request by ismay**
See #119. The prefixes for our stories were not very consistent. We had this:

Screenshot 2020-06-15 at 12 02 07

So `ui-forms` exports were at the root under `forms`, whereas `ui-widgets` was under `components/widgets`. `ui-core` was split up in `base`, `utility` and `core`.

I think a more clear organisation would be to just group exports under the underlying library name:

Screenshot 2020-06-15 at 12 04 14

In accordance with this I've also removed the ButtonBase component story, as that's not exported, so the user cannot do anything with it anyway. See the live preview here: https://deploy-preview-167--dhis2-ui.netlify.app/demo/

### CODE REVIEW

**Comment by Mohammer5** [comment]
I did like the distinction between components, utilities and forms (not happy with the names though). The distinction clearly communicated that if you want to create a dhis2 ui, you'd use the components. If you need some kind of utility that's more global or does not affect a component directly, you can see what's available in the `Utilities` section and `forms` shows that there are components made ready for plug'n'play use with RFF.

The distinction between `core` and `widgets` is something that'd be more confusing than helping in my opinion. Firstly even we - the developers - have struggled in the past with these terms, so it won't be clear to consumers either, secondly the architecture might change, so we'll have to modify out live docs here as well, which is confusing and thirdly we're trying to make consumers use the `ui` library which exports all components, so I think we could just put all components inside `Components` instead of further grouping them.

So how about this (or something similar):

```
* Components
* Utilities
* React final form adjusted
```

**Comment by ismay** [comment]
> I did like the distinction between components, utilities and forms (not happy with the names though). The distinction clearly communicated that if you want to create a dhis2 ui, you'd use the components. If you need some kind of utility that's more global or does not affect a component directly, you can see what's available in the `Utilities` section and `forms` shows that there are components made ready for plug'n'play use with RFF.
> 
> The distinction between `core` and `widgets` is something that'd be more confusing than helping in my opinion. Firstly even we - the developers - have struggled in the past with these terms, so it won't be clear to consumers either, secondly the architecture might change, so we'll have to modify out live docs here as well, which is confusing and thirdly we're trying to make consumers use the `ui` library which exports all components, so I think we could just put all components inside `Components` instead of further grouping them.
> 
> So how about this (or something similar):
> 
> ```
> * Components
> * Utilities
> * React final form adjusted
> ```

Yeah the thing is, even though all our components are exported from ui, they're ultimately still contained in these libs. What I like about using this for categorization is that it's an objective distinction. It's simple to understand and we don't have to have any discussion about it, which saves time and thinking.

The fact that it might not be as informative to a user whether a component lives in widgets or core, etc. is more an illustration of the fact that those library names aren't very useful. ui-forms has a very clear scope for instance, and knowing that a component lives in ui-forms tells me what kind of component I can expect.

What you're referring to is useful information in my opinion, but I think is more suitable for documentation. I think it requires a bit more explanation than just these categories. I.e.: these components are meant to be used in this way, those are meant to be used in that way. The current categorization did not tell me much (I don't know what is meant by a component being in Components, or a component being in Utilities).

So since it didn't add much, I thought it'd be simpler to a naming strategy that doesn't require any discussion about categorization, since that already occupies so much of our time.

**Comment by ismay** [comment]
@Mohammer5 and I talked about this on slack a bit. He mentioned that the library names might encourage importing from the specific libraries (which we don't want), and that it might end up just confusing users.

So we agreed to just remove the categorisation completely for now. Once we've found a categorisation that we're happy with, we can implement it then.

**Comment by ismay** [comment]
> LGTM, but I think we should give the others (cc @dhis2/front-end) a chance to have a look at this as well

Yeah I agree, it's quite a big change. I'll post it in UI.

**Pull request merged**
