### PR TITLE
fix: remove margin of first child conditionally for correct alignment

### LINKED ISSUE #92: SplitButton in ButtonStrip missing margin
`ButtonStrip` adds margins to child `Button`s, but not to child `SplitButton`. 

Adds margin (child `Button`)
image

Doesn't add margin (child `SplitButton`)
image

Correct spacing (child `Button`)
image

Incorrect spacing (child `SplitButton`)
image

### PR DESCRIPTION
**Pull request by Mohammer5**
Fixed #92 

I've also changed the prop type of `children` to `propTypes.node`, because a prop types error is thrown when providing only one child

### CODE REVIEW

**Comment by ismay** [comment]
I think @martinkrulltott needs this for something he's working on. Maybe we could do this in ui-core and then pull it into ui afterwards? Not sure what his timeframe is.

If not, feel free to move this issue back to ui: https://github.com/dhis2/ui-core/issues/889 so that we can close it after merging this.

**Comment by martinkrulltott** [comment]
> I think @martinkrulltott needs this for something he's working on. Maybe we could do this in ui-core and then pull it into ui afterwards? Not sure what his timeframe is.
It's needed for [DHIS2-8807](https://jira.dhis2.org/browse/DHIS2-8807) which is part of v35, so not urgent.

**Comment by ismay** [comment]
Ah ok, yeah in that case merging in ui seems like it'd be easier. What do you think @Mohammer5?

**Comment by Mohammer5** [comment]
Yeah, let's just keep in in `ui` to keep things as simple as possible

**Comment by ismay** [comment]
Issue for this topic: https://github.com/dhis2/ui/issues/89

**Comment by ismay** [comment]
> I think the best way to address this is to just wrap the children in a div and apply the correct margins there. That way we could get rid of the `:global(button)` selector, which is a weakness of this component.

That sounds good to me. Maybe the `Box`?

> I also seem to vaguely remember that at some point we discussed to remove this component, and that we would be introducing a `Spacer` component instead. I guess that even if that were true, we wouldn't be doing that now because that'd be a breaking change. So probably for not the suggestion above is more appropriate.

Maybe if we still want the spacer we could create an issue and add it to the v6 milestone

**Comment by Mohammer5** [comment]
Ok, so to sum it up: Wrap children with a `Box` and apply the margin there. Will do later

**Comment by Mohammer5** [comment]
I've updated the component and story. I'm using a `div`, not the `Box`. This way I don't have to use `styled-jsx`'s `resolve` function and can keep the all the styles in one `style` element. Also if the `Box`'s styles ever change, it won't affect this component.

**Pull request merged**
