### PR TITLE
ci: run 10x parallelization for Cypress tests

### PR DESCRIPTION
**Pull request by amcgee**

### CODE REVIEW

**Comment by ismay** [comment]
Nice. Does really cut down on the execution time (from 12:44 [here](https://github.com/dhis2/ui/pull/327)) to 3:58 in this PR.

**Comment by amcgee** [comment]
> Nice. Does really cut down on the execution time (from 12:44 here) to 3:58 in this PR.

Yep, I think it's an improvement - @varl has some more holistic changes in mind which he's mocked up as well.

The speed up isn't QUITE as drastic as the 12:44->3:58 implies, since this PR has a yarn cache hit while the dependabot PR has a cache miss, but I think we can definitely speed things up by increasing concurrency!

**Comment by amcgee** [comment]
Actually maybe that excludes the yarn install... this PR has an e2e test runtime of 6m while the 3x version with cache miss ran for 18m

**Comment by amcgee** [comment]
@varl do you think we should merge this or wait for the single-workflow change?

**Review by varl — APPROVED** [review]

**Comment by varl** [comment]
We might as well get the benefits of this immediately while i finish up the single workflow change.

**Pull request merged**
