### PR TITLE
docs(concepts): remove concepts

### PR DESCRIPTION
**Pull request by ismay**
I've gone through the concepts doc, and I think it's actually not very interesting to our users in its current form. I can see the use of an overview of our libraries, but I think this document is currently written more from our point of view, as developers, not for consumers of the lib.

I propose we remove this section, as in its current state I think it's a bit confusing to lib users, and move it to an issue, where we plan adding a `Developing` section. Then we can rewrite where necessary, and add this section back as an instruction to developers that want to contribute.

### CODE REVIEW

**Comment by amcgee** [comment]
@ismay I agree with this!  Should we move it to `CONTRIBUTING.md` in the repo (linked from the README) and open an issue to update it so we keep the information accessible to developers (mainly us)?

**Comment by amcgee** [comment]
Eventually we will probably want to expose contribution sections across all our docs, but I agree they shouldn't be co-mingled with consumer docs

**Comment by amcgee** [comment]
It could also move directly to a `Contributing` section of the docsite, but I think I agree it makes sense in GitHub until we have a consistent way to construct contribution documentation

**Comment by ismay** [comment]
> @ismay I agree with this! Should we move it to `CONTRIBUTING.md` in the repo (linked from the README) and open an issue to update it so we keep the information accessible to developers (mainly us)?

I was thinking of putting the current contents of the doc in an issue, but I could also put it in a PR. I don't think I'd publish it as is. There seem to still be areas that haven't fully resolved. We could discuss those in the PR.

**Comment by amcgee** [comment]
Sure, if you'd prefer to pull it out into an issue that's fine too, just thought it might be nice not to bury it too much as it's useful content for someone looking at this repo for the first time.  Will leave the decision up to you though!

**Comment by ismay** [comment]
I've moved it to contributing.md in the end. I see your point, and it's not as big of a deal if the document's not perfect yet.

**Pull request merged**
